# LEARN-Hub Production compose file using pre-built multi-arch images
# Usage: docker-compose -f compose.prod.yml up -d

services:
  postgres:
    image: postgres:17
    container_name: lhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-learn_hub_activities}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_DATA:-./pg_data}:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-learn_hub_activities}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  server:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-org/your-repo}/server:${IMAGE_TAG:-latest}
    container_name: lhub-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-5001}:5001"
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-learn_hub_activities}
      - PDF_PATH=/app/data/pdfs
    volumes:
      - ${PDF_PATH}:/app/data/pdfs
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "/app/.venv/bin/python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5001/api/hello', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  client:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-org/your-repo}/client:${IMAGE_TAG:-latest}
    container_name: lhub-client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT:-3001}:3001"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
