"""initial_migration

Revision ID: 1986b4a071aa
Revises:
Create Date: 2025-08-26 20:33:19.146165

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1986b4a071aa"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("age_min", sa.Integer(), nullable=False),
        sa.Column("age_max", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=50), nullable=False),
        sa.Column("bloom_level", sa.String(length=50), nullable=False),
        sa.Column("duration_min_minutes", sa.Integer(), nullable=False),
        sa.Column("duration_max_minutes", sa.Integer(), nullable=True),
        sa.Column("mental_load", sa.Enum("LOW", "MEDIUM", "HIGH", name="energylevel"), nullable=True),
        sa.Column("physical_energy", sa.Enum("LOW", "MEDIUM", "HIGH", name="energylevel"), nullable=True),
        sa.Column("prep_time_minutes", sa.Integer(), nullable=True),
        sa.Column("cleanup_time_minutes", sa.Integer(), nullable=True),
        sa.Column("pdf_path", sa.String(length=500), nullable=True),
        sa.Column("pdf_uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("resources_needed", sa.JSON(), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add performance indexes
    op.create_index("ix_activities_age_range", "activities", ["age_min", "age_max"])
    op.create_index("ix_activities_format", "activities", ["format"])
    op.create_index("ix_activities_bloom_level", "activities", ["bloom_level"])

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("role", sa.Enum("TEACHER", "ADMIN", name="userrole"), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "user_selections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_ids", sa.JSON(), nullable=False),
        sa.Column("search_criteria", sa.JSON(), nullable=False),
        sa.Column("ordering_method", sa.String(length=50), nullable=False),
        sa.Column("total_duration", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_selections_id"), "user_selections", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_selections_id"), table_name="user_selections")
    op.drop_table("user_selections")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    # Drop performance indexes
    op.drop_index("ix_activities_bloom_level", table_name="activities")
    op.drop_index("ix_activities_format", table_name="activities")
    op.drop_index("ix_activities_age_range", table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
