"""add_verification_codes_table

Revision ID: 2a3b4c5d6e7f
Revises: 1986b4a071aa
Create Date: 2025-09-07 22:18:07.837528

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a3b4c5d6e7f"
down_revision: str | Sequence[str] | None = "1986b4a071aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=6), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("used", sa.String(length=1), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_verification_codes_id"), "verification_codes", ["id"], unique=False)
    op.create_index("ix_verification_codes_user_id", "verification_codes", ["user_id"], unique=False)
    op.create_index("ix_verification_codes_code", "verification_codes", ["code"], unique=False)
    op.create_index("ix_verification_codes_expires_at", "verification_codes", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_verification_codes_expires_at", table_name="verification_codes")
    op.drop_index("ix_verification_codes_code", table_name="verification_codes")
    op.drop_index("ix_verification_codes_user_id", table_name="verification_codes")
    op.drop_index(op.f("ix_verification_codes_id"), table_name="verification_codes")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
