"""rename_favorites_to_favourites_and_simplify

Revision ID: 841a75f1cd58
Revises: dddea8cbfe6a
Create Date: 2025-10-19 16:36:22.961753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "841a75f1cd58"
down_revision: str | Sequence[str] | None = "dddea8cbfe6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create new user_favourites table
    op.create_table(
        "user_favourites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("favourite_type", sa.String(length=20), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=True),
        sa.Column("activity_ids", sa.JSON(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_favourites_id"), "user_favourites", ["id"], unique=False)

    # Migrate data from old table to new table
    op.execute(
        """
        INSERT INTO user_favourites (id, user_id, favourite_type, activity_id, activity_ids, name, created_at)
        SELECT 
            id,
            user_id,
            favorite_type,
            activity_id,
            activity_ids,
            name,
            created_at
        FROM user_favorites
    """
    )

    # Drop old table
    op.drop_index(op.f("ix_user_favorites_id"), table_name="user_favorites")
    op.drop_table("user_favorites")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_favorites",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("activity_ids", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("search_criteria", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("ordering_method", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("total_duration", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.Column("favorite_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("activity_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("user_favorites_user_id_fkey")),
        sa.PrimaryKeyConstraint("id", name=op.f("user_favorites_pkey")),
    )
    op.create_index(op.f("ix_user_favorites_id"), "user_favorites", ["id"], unique=False)
    op.drop_index(op.f("ix_user_favourites_id"), table_name="user_favourites")
    op.drop_table("user_favourites")
    # ### end Alembic commands ###
