"""update_user_favorites_for_activities_and_lesson_plans

Revision ID: dddea8cbfe6a
Revises: c4029a75d31e
Create Date: 2025-10-19 16:30:24.648238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dddea8cbfe6a"
down_revision: str | Sequence[str] | None = "c4029a75d31e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new columns with nullable=True first
    op.add_column("user_favorites", sa.Column("favorite_type", sa.String(length=20), nullable=True))
    op.add_column("user_favorites", sa.Column("activity_id", sa.Integer(), nullable=True))
    op.add_column("user_favorites", sa.Column("name", sa.String(length=255), nullable=True))

    # Update existing records to have favorite_type = 'lesson_plan'
    op.execute("UPDATE user_favorites SET favorite_type = 'lesson_plan' WHERE favorite_type IS NULL")

    # Now make favorite_type NOT NULL
    op.alter_column("user_favorites", "favorite_type", nullable=False)

    # Make other columns nullable
    op.alter_column(
        "user_favorites", "activity_ids", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "user_favorites", "search_criteria", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=True
    )
    op.alter_column("user_favorites", "ordering_method", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("user_favorites", "total_duration", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_favorites", "total_duration", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("user_favorites", "ordering_method", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.alter_column(
        "user_favorites", "search_criteria", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "user_favorites", "activity_ids", existing_type=postgresql.JSON(astext_type=sa.Text()), nullable=False
    )
    op.drop_column("user_favorites", "name")
    op.drop_column("user_favorites", "activity_id")
    op.drop_column("user_favorites", "favorite_type")
    # ### end Alembic commands ###
