package com.learnhub.documentmanagement.service;

import jakarta.xml.bind.JAXBElement;
import java.math.BigInteger;
import java.util.List;
import org.docx4j.jaxb.Context;
import org.docx4j.wml.*;
import org.springframework.stereotype.Component;

/**
 * Helper for Artikulationsschema table layout in DOCX. Applies fixed column
 * widths and full-width styling to tables generated by
 * {@link MarkdownToDocxService}.
 *
 * <p>
 * Extracted from {@link MarkdownToDocxService} to keep the main service class
 * focused on orchestration.
 * </p>
 */
@Component
public class DocxTableHelper {

	private static final int[] ARTIKULATIONSSCHEMA_COLUMN_WIDTHS_PERCENT = {8, 12, 38, 10, 16, 16};
	private static final ObjectFactory WML_FACTORY = Context.getWmlObjectFactory();

	/**
	 * Apply Artikulationsschema-specific table layout (fixed column widths) to
	 * all tables in the given element list.
	 *
	 * @param elements
	 *            DOCX elements (paragraphs, tables, etc.)
	 * @param landscape
	 *            true if the page is landscape, false if portrait
	 * @param pageWidth
	 *            page width in twips
	 * @param marginLeft
	 *            left margin in twips
	 * @param marginRight
	 *            right margin in twips
	 */
	public void applyArtikulationsschemaTableLayout(List<Object> elements, boolean landscape, int pageWidth,
			int pageHeight, int marginLeft, int marginRight) {
		int totalWidthTwips = (landscape ? pageWidth : pageHeight) - marginLeft - marginRight;
		int[] columnWidths = toAbsoluteColumnWidths(totalWidthTwips);

		for (Object element : elements) {
			Object value = unwrap(element);
			if (value instanceof Tbl table) {
				configureFullWidthTable(table, totalWidthTwips, columnWidths);
			}
		}
	}

	int[] toAbsoluteColumnWidths(int totalWidthTwips) {
		int[] widths = new int[ARTIKULATIONSSCHEMA_COLUMN_WIDTHS_PERCENT.length];
		int consumed = 0;

		for (int i = 0; i < ARTIKULATIONSSCHEMA_COLUMN_WIDTHS_PERCENT.length; i++) {
			if (i == ARTIKULATIONSSCHEMA_COLUMN_WIDTHS_PERCENT.length - 1) {
				widths[i] = totalWidthTwips - consumed;
			} else {
				widths[i] = totalWidthTwips * ARTIKULATIONSSCHEMA_COLUMN_WIDTHS_PERCENT[i] / 100;
				consumed += widths[i];
			}
		}

		return widths;
	}

	void configureFullWidthTable(Tbl table, int totalWidthTwips, int[] columnWidths) {
		TblPr tblPr = table.getTblPr();
		if (tblPr == null) {
			tblPr = WML_FACTORY.createTblPr();
			table.setTblPr(tblPr);
		}

		TblWidth tblWidth = WML_FACTORY.createTblWidth();
		tblWidth.setType(TblWidth.TYPE_DXA);
		tblWidth.setW(BigInteger.valueOf(totalWidthTwips));
		tblPr.setTblW(tblWidth);

		CTTblLayoutType layout = WML_FACTORY.createCTTblLayoutType();
		layout.setType(STTblLayoutType.FIXED);
		tblPr.setTblLayout(layout);

		TblGrid tblGrid = table.getTblGrid();
		if (tblGrid == null) {
			tblGrid = WML_FACTORY.createTblGrid();
			table.setTblGrid(tblGrid);
		}
		tblGrid.getGridCol().clear();
		for (int width : columnWidths) {
			TblGridCol gridCol = WML_FACTORY.createTblGridCol();
			gridCol.setW(BigInteger.valueOf(width));
			tblGrid.getGridCol().add(gridCol);
		}

		for (Object rowObject : table.getContent()) {
			Object rowValue = unwrap(rowObject);
			if (!(rowValue instanceof Tr row)) {
				continue;
			}

			int columnIndex = 0;
			for (Object cellObject : row.getContent()) {
				Object cellValue = unwrap(cellObject);
				if (!(cellValue instanceof Tc cell)) {
					continue;
				}

				int span = getGridSpan(cell);
				int cellWidthTwips = 0;
				for (int i = 0; i < span && columnIndex + i < columnWidths.length; i++) {
					cellWidthTwips += columnWidths[columnIndex + i];
				}
				setCellWidth(cell, cellWidthTwips);
				columnIndex += Math.max(span, 1);
			}
		}
	}

	private int getGridSpan(Tc cell) {
		TcPr tcPr = cell.getTcPr();
		if (tcPr == null || tcPr.getGridSpan() == null || tcPr.getGridSpan().getVal() == null) {
			return 1;
		}
		return Math.max(tcPr.getGridSpan().getVal().intValue(), 1);
	}

	private void setCellWidth(Tc cell, int widthTwips) {
		TcPr tcPr = cell.getTcPr();
		if (tcPr == null) {
			tcPr = WML_FACTORY.createTcPr();
			cell.setTcPr(tcPr);
		}

		TblWidth tcWidth = WML_FACTORY.createTblWidth();
		tcWidth.setType(TblWidth.TYPE_DXA);
		tcWidth.setW(BigInteger.valueOf(widthTwips));
		tcPr.setTcW(tcWidth);
	}

	private Object unwrap(Object value) {
		return value instanceof JAXBElement<?> element ? element.getValue() : value;
	}
}
