package com.learnhub.documentmanagement.service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import org.apache.poi.util.Units;
import org.apache.poi.wp.usermodel.HeaderFooterType;
import org.apache.poi.xwpf.usermodel.*;
import org.apache.xmlbeans.XmlCursor;
import org.openxmlformats.schemas.drawingml.x2006.main.CTPositiveSize2D;
import org.openxmlformats.schemas.drawingml.x2006.wordprocessingDrawing.CTAnchor;
import org.openxmlformats.schemas.drawingml.x2006.wordprocessingDrawing.CTInline;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

/**
 * Post-processes a DOCX file generated by LibreOffice to add LEARN-Hub headers,
 * footers, and page orientation settings that LibreOffice cannot derive from
 * HTML/CSS.
 */
@Component
public class DocxPostProcessor {

	private static final Logger logger = LoggerFactory.getLogger(DocxPostProcessor.class);

	private static final String LOGO_PATH = "templates/markdown/header-logo.png";
	private static final DateTimeFormatter FOOTER_DATE_FORMATTER = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
	private static final String FOOTER_BRANDING_TEXT = "LEARN-Hub \u2013 a TUM Applied Education Technologies application \u00B7 aet.cit.tum.de";
	private static final String WORKSHEET_FONT_FAMILY = "Comic Sans MS";

	private static final int HEADER_FONT_SIZE = 10;
	private static final int FOOTER_FONT_SIZE = 7;
	private static final String ACCENT_COLOR = "555555";
	private static final long LANDSCAPE_IMAGE_MAX_HEIGHT_MM = 43L;
	private static final long PORTRAIT_IMAGE_MAX_HEIGHT_MM = 64L;
	private static final long EMUS_PER_MM = 36000L;
	private static final long EMUS_PER_TWIP = 635L;
	private static final long PAGE_MARGIN_LEFT_RIGHT_TWIPS = 1200L;

	/** A4 dimensions in twips (twentieths of a point). */
	private static final long A4_SHORT = 11906; // 210mm
	private static final long A4_LONG = 16838; // 297mm

	/**
	 * Post-process a DOCX byte array: set page orientation and add header/footer.
	 */
	public byte[] process(byte[] docxBytes, boolean landscape, String activityName) throws IOException {
		try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(docxBytes))) {
			setPageOrientation(doc, landscape);
			enforceImageSizeCaps(doc, landscape);
			addHeaderAndFooter(doc, activityName);
			applyWorksheetFontFamily(doc);

			try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
				doc.write(out);
				return out.toByteArray();
			}
		}
	}

	/**
	 * Merge multiple individually-processed DOCX byte arrays into a single
	 * document. Each section retains its own page orientation. Headers and footers
	 * are created once and referenced by all sections.
	 *
	 * @param sectionDocxBytes
	 *            list of DOCX byte arrays, one per section (already converted by
	 *            LibreOffice, but NOT yet post-processed)
	 * @param landscapes
	 *            orientation per section
	 * @param activityName
	 *            the activity name shown in the header
	 */
	public byte[] mergeSections(List<byte[]> sectionDocxBytes, List<Boolean> landscapes, String activityName)
			throws IOException {
		// Use the first section as the base document so its styles (heading styles
		// etc.)
		// are naturally inherited by the merged result.
		try (XWPFDocument merged = new XWPFDocument(new ByteArrayInputStream(sectionDocxBytes.get(0)))) {
			// Clear all body content from the base document
			clearBodyElements(merged);

			// Set up header/footer once on the merged document
			addHeaderAndFooter(merged, activityName);

			for (int i = 0; i < sectionDocxBytes.size(); i++) {
				try (XWPFDocument section = new XWPFDocument(new ByteArrayInputStream(sectionDocxBytes.get(i)))) {
					enforceImageSizeCaps(section, landscapes.get(i));

					// Before appending content (except for the first section), insert a
					// section-break paragraph that carries the PREVIOUS section's orientation.
					if (i > 0) {
						addSectionBreak(merged, landscapes.get(i - 1));
					}

					// Copy all body elements (paragraphs and tables) from the section
					for (IBodyElement element : section.getBodyElements()) {
						if (element instanceof XWPFParagraph srcPara) {
							XWPFParagraph newPara = merged.createParagraph();
							copyParagraph(srcPara, newPara);
						} else if (element instanceof XWPFTable srcTable) {
							XWPFTable newTable = merged.createTable();
							copyTable(srcTable, newTable);
						}
					}
				}
			}

			// Set the body-level sectPr for the LAST section's orientation
			setPageOrientation(merged, landscapes.get(landscapes.size() - 1));
			applyWorksheetFontFamily(merged);

			try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
				merged.write(out);
				return out.toByteArray();
			}
		}
	}

	/**
	 * Insert a paragraph with an inline section break (next page) that sets the
	 * given orientation. In DOCX, mid-document section breaks are stored as a
	 * SectPr inside the last paragraph's PPr of the preceding section.
	 */
	private void addSectionBreak(XWPFDocument doc, boolean landscape) {
		XWPFParagraph breakPara = doc.createParagraph();
		CTP ctp = breakPara.getCTP();
		CTPPr pPr = ctp.isSetPPr() ? ctp.getPPr() : ctp.addNewPPr();
		CTSectPr sectPr = pPr.addNewSectPr();
		sectPr.addNewType().setVal(STSectionMark.NEXT_PAGE);
		applyPageGeometry(sectPr, landscape);

		// Reference the document's header/footer so they appear in this section too
		CTSectPr bodySectPr = doc.getDocument().getBody().getSectPr();
		if (bodySectPr != null) {
			for (CTHdrFtrRef ref : bodySectPr.getHeaderReferenceList()) {
				CTHdrFtrRef newRef = sectPr.addNewHeaderReference();
				newRef.setType(ref.getType());
				newRef.setId(ref.getId());
			}
			for (CTHdrFtrRef ref : bodySectPr.getFooterReferenceList()) {
				CTHdrFtrRef newRef = sectPr.addNewFooterReference();
				newRef.setType(ref.getType());
				newRef.setId(ref.getId());
			}
		}
	}

	private void clearBodyElements(XWPFDocument doc) {
		int size = doc.getBodyElements().size();
		for (int i = size - 1; i >= 0; i--) {
			doc.removeBodyElement(i);
		}
	}

	private void copyParagraph(XWPFParagraph src, XWPFParagraph dest) {
		// Deep copy via XML
		dest.getCTP().set(src.getCTP().copy());
	}

	private void copyTable(XWPFTable src, XWPFTable dest) {
		dest.getCTTbl().set(src.getCTTbl().copy());
	}

	private void applyWorksheetFontFamily(XWPFDocument doc) {
		applyWorksheetFontFamily(doc.getBodyElements());
		for (XWPFHeader header : doc.getHeaderList()) {
			applyWorksheetFontFamily(header.getBodyElements());
		}
		for (XWPFFooter footer : doc.getFooterList()) {
			applyWorksheetFontFamily(footer.getBodyElements());
		}
	}

	private void applyWorksheetFontFamily(List<IBodyElement> bodyElements) {
		for (IBodyElement element : bodyElements) {
			if (element instanceof XWPFParagraph paragraph) {
				applyWorksheetFontFamily(paragraph);
			} else if (element instanceof XWPFTable table) {
				applyWorksheetFontFamily(table);
			}
		}
	}

	private void applyWorksheetFontFamily(XWPFTable table) {
		for (XWPFTableRow row : table.getRows()) {
			for (XWPFTableCell cell : row.getTableCells()) {
				applyWorksheetFontFamily(cell.getBodyElements());
			}
		}
	}

	private void applyWorksheetFontFamily(XWPFParagraph paragraph) {
		for (XWPFRun run : paragraph.getRuns()) {
			CTRPr runProperties = run.getCTR().isSetRPr() ? run.getCTR().getRPr() : run.getCTR().addNewRPr();
			CTFonts fonts = runProperties.sizeOfRFontsArray() > 0
					? runProperties.getRFontsArray(0)
					: runProperties.addNewRFonts();
			fonts.setAscii(WORKSHEET_FONT_FAMILY);
			fonts.setHAnsi(WORKSHEET_FONT_FAMILY);
			fonts.setCs(WORKSHEET_FONT_FAMILY);
			fonts.setEastAsia(WORKSHEET_FONT_FAMILY);
			run.setFontFamily(WORKSHEET_FONT_FAMILY);
		}
	}

	private void enforceImageSizeCaps(XWPFDocument doc, boolean landscape) {
		long maxWidthEmu = ((landscape ? A4_LONG : A4_SHORT) - PAGE_MARGIN_LEFT_RIGHT_TWIPS) * EMUS_PER_TWIP;
		long maxHeightEmu = (landscape ? LANDSCAPE_IMAGE_MAX_HEIGHT_MM : PORTRAIT_IMAGE_MAX_HEIGHT_MM) * EMUS_PER_MM;
		enforceImageSizeCaps(doc.getBodyElements(), maxWidthEmu, maxHeightEmu);
	}

	private void enforceImageSizeCaps(List<IBodyElement> bodyElements, long maxWidthEmu, long maxHeightEmu) {
		for (IBodyElement element : bodyElements) {
			if (element instanceof XWPFParagraph paragraph) {
				enforceImageSizeCaps(paragraph, maxWidthEmu, maxHeightEmu);
			} else if (element instanceof XWPFTable table) {
				enforceImageSizeCaps(table, maxWidthEmu, maxHeightEmu);
			}
		}
	}

	private void enforceImageSizeCaps(XWPFTable table, long maxWidthEmu, long maxHeightEmu) {
		for (XWPFTableRow row : table.getRows()) {
			for (XWPFTableCell cell : row.getTableCells()) {
				enforceImageSizeCaps(cell.getBodyElements(), maxWidthEmu, maxHeightEmu);
			}
		}
	}

	private void enforceImageSizeCaps(XWPFParagraph paragraph, long maxWidthEmu, long maxHeightEmu) {
		for (XWPFRun run : paragraph.getRuns()) {
			for (CTDrawing drawing : run.getCTR().getDrawingList()) {
				for (CTInline inline : drawing.getInlineList()) {
					scaleDownExtent(inline.getExtent(), maxWidthEmu, maxHeightEmu);
				}
				for (CTAnchor anchor : drawing.getAnchorList()) {
					scaleDownExtent(anchor.getExtent(), maxWidthEmu, maxHeightEmu);
				}
			}
		}
	}

	private void scaleDownExtent(CTPositiveSize2D extent, long maxWidthEmu, long maxHeightEmu) {
		if (extent == null) {
			return;
		}

		long width = extent.getCx();
		long height = extent.getCy();
		if (width <= 0 || height <= 0) {
			return;
		}

		double scale = Math.min(1d, Math.min((double) maxWidthEmu / width, (double) maxHeightEmu / height));
		if (scale >= 1d) {
			return;
		}

		extent.setCx(Math.max(1L, Math.round(width * scale)));
		extent.setCy(Math.max(1L, Math.round(height * scale)));
	}

	private void setPageOrientation(XWPFDocument doc, boolean landscape) {
		CTSectPr sectPr = doc.getDocument().getBody().getSectPr();
		if (sectPr == null) {
			sectPr = doc.getDocument().getBody().addNewSectPr();
		}
		applyPageGeometry(sectPr, landscape);
	}

	private void applyPageGeometry(CTSectPr sectPr, boolean landscape) {
		CTPageSz pgSz = sectPr.isSetPgSz() ? sectPr.getPgSz() : sectPr.addNewPgSz();
		if (landscape) {
			pgSz.setW(BigInteger.valueOf(A4_LONG));
			pgSz.setH(BigInteger.valueOf(A4_SHORT));
			pgSz.setOrient(STPageOrientation.LANDSCAPE);
		} else {
			pgSz.setW(BigInteger.valueOf(A4_SHORT));
			pgSz.setH(BigInteger.valueOf(A4_LONG));
			pgSz.setOrient(STPageOrientation.PORTRAIT);
		}

		CTPageMar pgMar = sectPr.isSetPgMar() ? sectPr.getPgMar() : sectPr.addNewPgMar();
		pgMar.setTop(BigInteger.valueOf(850));
		pgMar.setBottom(BigInteger.valueOf(750));
		pgMar.setLeft(BigInteger.valueOf(600));
		pgMar.setRight(BigInteger.valueOf(600));
		pgMar.setHeader(BigInteger.valueOf(250));
		pgMar.setFooter(BigInteger.valueOf(250));
	}

	private void addHeaderAndFooter(XWPFDocument doc, String activityName) throws IOException {
		// Build header
		XWPFHeader header = doc.createHeader(HeaderFooterType.DEFAULT);
		clearParagraphs(header);
		XWPFParagraph headerPara = header.createParagraph();
		headerPara.setAlignment(ParagraphAlignment.RIGHT);
		if (activityName != null && !activityName.isBlank()) {
			XWPFRun nameRun = headerPara.createRun();
			nameRun.setText(activityName + "  ");
			nameRun.setFontSize(HEADER_FONT_SIZE);
			nameRun.setColor(ACCENT_COLOR);
			nameRun.setFontFamily(WORKSHEET_FONT_FAMILY);
		}
		addLogoToHeader(headerPara);

		// Build footer
		XWPFFooter footer = doc.createFooter(HeaderFooterType.DEFAULT);
		clearParagraphs(footer);
		buildFooterTable(footer);
	}

	private void clearParagraphs(XWPFHeaderFooter hf) {
		java.util.List<XWPFParagraph> paragraphs = hf.getParagraphs();
		for (int i = paragraphs.size() - 1; i >= 0; i--) {
			hf.removeParagraph(paragraphs.get(i));
		}
	}

	private void addLogoToHeader(XWPFParagraph para) {
		try (InputStream logoStream = new ClassPathResource(LOGO_PATH).getInputStream()) {
			XWPFRun imageRun = para.createRun();
			imageRun.addPicture(logoStream, XWPFDocument.PICTURE_TYPE_PNG, "header-logo.png", Units.toEMU(21),
					Units.toEMU(22));
		} catch (Exception e) {
			org.slf4j.LoggerFactory.getLogger(DocxPostProcessor.class).warn("Failed to add logo to DOCX header", e);
		}
	}

	private void buildFooterTable(XWPFFooter footer) {
		XWPFTable table = footer.createTable(1, 3);
		table.setWidth("100%");

		// Remove borders
		CTTblPr tblPr = table.getCTTbl().getTblPr();
		if (tblPr == null) {
			tblPr = table.getCTTbl().addNewTblPr();
		}
		CTTblBorders borders = tblPr.isSetTblBorders() ? tblPr.getTblBorders() : tblPr.addNewTblBorders();
		setNilBorder(borders.addNewTop());
		setNilBorder(borders.addNewBottom());
		setNilBorder(borders.addNewLeft());
		setNilBorder(borders.addNewRight());
		setNilBorder(borders.addNewInsideH());
		setNilBorder(borders.addNewInsideV());

		// Left: date
		setFooterCellText(table.getRow(0).getCell(0), LocalDateTime.now().format(FOOTER_DATE_FORMATTER), STJc.LEFT);

		// Center: branding
		setFooterCellText(table.getRow(0).getCell(1), FOOTER_BRANDING_TEXT, STJc.CENTER);

		// Right: page number
		setFooterPageNumber(table.getRow(0).getCell(2));
	}

	private void setFooterCellText(XWPFTableCell cell, String text, STJc.Enum alignment) {
		// Use existing first paragraph or create one
		XWPFParagraph para = cell.getParagraphArray(0);
		if (para == null) {
			para = cell.addParagraph();
		}
		CTPPr pPr = para.getCTP().addNewPPr();
		pPr.addNewJc().setVal(alignment);

		XWPFRun run = para.createRun();
		run.setText(text);
		run.setFontSize(FOOTER_FONT_SIZE);
		run.setColor(ACCENT_COLOR);
		run.setFontFamily(WORKSHEET_FONT_FAMILY);
	}

	private void setFooterPageNumber(XWPFTableCell cell) {
		XWPFParagraph para = cell.getParagraphArray(0);
		if (para == null) {
			para = cell.addParagraph();
		}
		CTPPr pPr = para.getCTP().addNewPPr();
		pPr.addNewJc().setVal(STJc.RIGHT);

		// "Page "
		XWPFRun prefixRun = para.createRun();
		prefixRun.setText("Page ");
		prefixRun.setFontSize(FOOTER_FONT_SIZE);
		prefixRun.setColor(ACCENT_COLOR);
		prefixRun.setFontFamily(WORKSHEET_FONT_FAMILY);

		// PAGE field
		addSimpleField(para, "PAGE");

		// " of "
		XWPFRun ofRun = para.createRun();
		ofRun.setText(" of ");
		ofRun.setFontSize(FOOTER_FONT_SIZE);
		ofRun.setColor(ACCENT_COLOR);
		ofRun.setFontFamily(WORKSHEET_FONT_FAMILY);

		// NUMPAGES field
		addSimpleField(para, "NUMPAGES");
	}

	private void addSimpleField(XWPFParagraph para, String fieldName) {
		CTSimpleField field = para.getCTP().addNewFldSimple();
		field.setInstr(" " + fieldName + " ");
		CTR run = field.addNewR();
		CTRPr rPr = run.addNewRPr();
		rPr.addNewSz().setVal(BigInteger.valueOf(FOOTER_FONT_SIZE * 2L));
		rPr.addNewSzCs().setVal(BigInteger.valueOf(FOOTER_FONT_SIZE * 2L));
		rPr.addNewColor().setVal(ACCENT_COLOR);
		CTFonts fonts = rPr.addNewRFonts();
		fonts.setAscii(WORKSHEET_FONT_FAMILY);
		fonts.setHAnsi(WORKSHEET_FONT_FAMILY);
		fonts.setCs(WORKSHEET_FONT_FAMILY);
		fonts.setEastAsia(WORKSHEET_FONT_FAMILY);
	}

	private void setNilBorder(CTBorder border) {
		border.setVal(STBorder.NIL);
	}
}
