package com.learnhub.documentmanagement.service;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import org.apache.poi.util.Units;
import org.apache.poi.wp.usermodel.HeaderFooterType;
import org.apache.poi.xwpf.usermodel.*;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.*;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

/**
 * Post-processes a DOCX file generated by LibreOffice to add LEARN-Hub headers,
 * footers, and page orientation settings that LibreOffice cannot derive from
 * HTML/CSS.
 */
@Component
public class DocxPostProcessor {

	private static final String LOGO_PATH = "templates/markdown/header-logo.png";
	private static final DateTimeFormatter FOOTER_DATE_FORMATTER = DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm");
	private static final String FOOTER_BRANDING_TEXT = "LEARN-Hub \u2013 a TUM Applied Education Technologies application \u00B7 aet.cit.tum.de";

	private static final int HEADER_FONT_SIZE = 10;
	private static final int FOOTER_FONT_SIZE = 7;
	private static final String ACCENT_COLOR = "555555";

	/** A4 dimensions in twips (twentieths of a point). */
	private static final long A4_SHORT = 11906; // 210mm
	private static final long A4_LONG = 16838; // 297mm

	/**
	 * Post-process a DOCX byte array: set page orientation and add header/footer.
	 */
	public byte[] process(byte[] docxBytes, boolean landscape, String activityName) throws IOException {
		try (XWPFDocument doc = new XWPFDocument(new ByteArrayInputStream(docxBytes))) {
			setPageOrientation(doc, landscape);
			addHeaderAndFooter(doc, activityName);

			try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
				doc.write(out);
				return out.toByteArray();
			}
		}
	}

	/**
	 * Post-process a merged DOCX. Uses the first section's orientation.
	 */
	public byte[] processMerged(byte[] docxBytes, java.util.List<Boolean> landscapes, String activityName)
			throws IOException {
		return process(docxBytes, landscapes.get(0), activityName);
	}

	private void setPageOrientation(XWPFDocument doc, boolean landscape) {
		CTSectPr sectPr = doc.getDocument().getBody().getSectPr();
		if (sectPr == null) {
			sectPr = doc.getDocument().getBody().addNewSectPr();
		}

		CTPageSz pgSz = sectPr.isSetPgSz() ? sectPr.getPgSz() : sectPr.addNewPgSz();
		if (landscape) {
			pgSz.setW(BigInteger.valueOf(A4_LONG));
			pgSz.setH(BigInteger.valueOf(A4_SHORT));
			pgSz.setOrient(STPageOrientation.LANDSCAPE);
		} else {
			pgSz.setW(BigInteger.valueOf(A4_SHORT));
			pgSz.setH(BigInteger.valueOf(A4_LONG));
			pgSz.setOrient(STPageOrientation.PORTRAIT);
		}

		CTPageMar pgMar = sectPr.isSetPgMar() ? sectPr.getPgMar() : sectPr.addNewPgMar();
		pgMar.setTop(BigInteger.valueOf(850));
		pgMar.setBottom(BigInteger.valueOf(750));
		pgMar.setLeft(BigInteger.valueOf(600));
		pgMar.setRight(BigInteger.valueOf(600));
		pgMar.setHeader(BigInteger.valueOf(250));
		pgMar.setFooter(BigInteger.valueOf(250));
	}

	private void addHeaderAndFooter(XWPFDocument doc, String activityName) throws IOException {
		// Build header
		XWPFHeader header = doc.createHeader(HeaderFooterType.DEFAULT);
		clearParagraphs(header);
		XWPFParagraph headerPara = header.createParagraph();
		headerPara.setAlignment(ParagraphAlignment.RIGHT);
		if (activityName != null && !activityName.isBlank()) {
			XWPFRun nameRun = headerPara.createRun();
			nameRun.setText(activityName + "  ");
			nameRun.setFontSize(HEADER_FONT_SIZE);
			nameRun.setColor(ACCENT_COLOR);
		}
		addLogoToHeader(headerPara);

		// Build footer
		XWPFFooter footer = doc.createFooter(HeaderFooterType.DEFAULT);
		clearParagraphs(footer);
		buildFooterTable(footer);
	}

	private void clearParagraphs(XWPFHeaderFooter hf) {
		java.util.List<XWPFParagraph> paragraphs = hf.getParagraphs();
		for (int i = paragraphs.size() - 1; i >= 0; i--) {
			hf.removeParagraph(paragraphs.get(i));
		}
	}

	private void addLogoToHeader(XWPFParagraph para) {
		try (InputStream logoStream = new ClassPathResource(LOGO_PATH).getInputStream()) {
			XWPFRun imageRun = para.createRun();
			imageRun.addPicture(logoStream, XWPFDocument.PICTURE_TYPE_PNG, "header-logo.png",
					Units.toEMU(21), Units.toEMU(22));
		} catch (Exception e) {
			org.slf4j.LoggerFactory.getLogger(DocxPostProcessor.class)
					.warn("Failed to add logo to DOCX header", e);
		}
	}

	private void buildFooterTable(XWPFFooter footer) {
		XWPFTable table = footer.createTable(1, 3);
		table.setWidth("100%");

		// Remove borders
		CTTblPr tblPr = table.getCTTbl().getTblPr();
		if (tblPr == null) {
			tblPr = table.getCTTbl().addNewTblPr();
		}
		CTTblBorders borders = tblPr.isSetTblBorders() ? tblPr.getTblBorders() : tblPr.addNewTblBorders();
		setNilBorder(borders.addNewTop());
		setNilBorder(borders.addNewBottom());
		setNilBorder(borders.addNewLeft());
		setNilBorder(borders.addNewRight());
		setNilBorder(borders.addNewInsideH());
		setNilBorder(borders.addNewInsideV());

		// Left: date
		setFooterCellText(table.getRow(0).getCell(0), LocalDateTime.now().format(FOOTER_DATE_FORMATTER), STJc.LEFT);

		// Center: branding
		setFooterCellText(table.getRow(0).getCell(1), FOOTER_BRANDING_TEXT, STJc.CENTER);

		// Right: page number
		setFooterPageNumber(table.getRow(0).getCell(2));
	}

	private void setFooterCellText(XWPFTableCell cell, String text, STJc.Enum alignment) {
		// Use existing first paragraph or create one
		XWPFParagraph para = cell.getParagraphArray(0);
		if (para == null) {
			para = cell.addParagraph();
		}
		CTPPr pPr = para.getCTP().addNewPPr();
		pPr.addNewJc().setVal(alignment);

		XWPFRun run = para.createRun();
		run.setText(text);
		run.setFontSize(FOOTER_FONT_SIZE);
		run.setColor(ACCENT_COLOR);
	}

	private void setFooterPageNumber(XWPFTableCell cell) {
		XWPFParagraph para = cell.getParagraphArray(0);
		if (para == null) {
			para = cell.addParagraph();
		}
		CTPPr pPr = para.getCTP().addNewPPr();
		pPr.addNewJc().setVal(STJc.RIGHT);

		// "Page "
		XWPFRun prefixRun = para.createRun();
		prefixRun.setText("Page ");
		prefixRun.setFontSize(FOOTER_FONT_SIZE);
		prefixRun.setColor(ACCENT_COLOR);

		// PAGE field
		addSimpleField(para, "PAGE");

		// " of "
		XWPFRun ofRun = para.createRun();
		ofRun.setText(" of ");
		ofRun.setFontSize(FOOTER_FONT_SIZE);
		ofRun.setColor(ACCENT_COLOR);

		// NUMPAGES field
		addSimpleField(para, "NUMPAGES");
	}

	private void addSimpleField(XWPFParagraph para, String fieldName) {
		CTSimpleField field = para.getCTP().addNewFldSimple();
		field.setInstr(" " + fieldName + " ");
		CTR run = field.addNewR();
		CTRPr rPr = run.addNewRPr();
		rPr.addNewSz().setVal(BigInteger.valueOf(FOOTER_FONT_SIZE * 2L));
		rPr.addNewSzCs().setVal(BigInteger.valueOf(FOOTER_FONT_SIZE * 2L));
		rPr.addNewColor().setVal(ACCENT_COLOR);
	}

	private void setNilBorder(CTBorder border) {
		border.setVal(STBorder.NIL);
	}
}
