package com.learnhub.documentmanagement.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.parser.PdfTextExtractor;
import com.itextpdf.kernel.utils.PdfMerger;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.learnhub.activitymanagement.dto.response.LessonPlanInfoResponse;
import com.learnhub.activitymanagement.entity.Activity;
import com.learnhub.activitymanagement.repository.ActivityRepository;
import com.learnhub.documentmanagement.entity.PDFDocument;
import com.learnhub.documentmanagement.repository.PDFDocumentRepository;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class PDFService {

	private static final Logger logger = LoggerFactory.getLogger(PDFService.class);
	private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
	private static final int MAX_CACHE_SIZE = 100;
	private static final long CACHE_TTL_MINUTES = 60;

	@Autowired
	private PDFDocumentRepository pdfDocumentRepository;

	@Autowired
	private ActivityRepository activityRepository;

	@Autowired
	private LLMService llmService;

	@Value("${pdf.storage.path:/app/data/pdfs}")
	private String pdfStoragePath;

	private final ConcurrentHashMap<UUID, CachedPdf> pdfCache = new ConcurrentHashMap<>();

	/**
	 * In-memory representation of a PDF that has been uploaded but not yet
	 * persisted.
	 */
	static class CachedPdf {

		final byte[] content;
		final String originalFilename;
		final LocalDateTime uploadedAt;
		String extractedFields = "{}";
		String confidenceScore;
		String extractionQuality;

		CachedPdf(byte[] content, String originalFilename) {
			this.content = content;
			this.originalFilename = originalFilename;
			this.uploadedAt = LocalDateTime.now();
		}
	}

	/**
	 * Cache PDF in memory without persisting to filesystem or database. Returns a
	 * UUID key that can later be passed to {@link #finalizePdf(UUID)} when the
	 * connected activity is created.
	 */
	public UUID cachePdf(byte[] pdfContent, String filename) {
		if (pdfCache.size() >= MAX_CACHE_SIZE) {
			evictOldestCacheEntry();
		}

		UUID cacheKey = UUID.randomUUID();
		pdfCache.put(cacheKey, new CachedPdf(pdfContent, filename));
		logger.debug("PDF cached with key={}, originalFilename={}", cacheKey, filename);
		return cacheKey;
	}

	/**
	 * Persist a previously cached PDF to the filesystem and database. JPA
	 * auto-generates the document ID. Returns the generated document ID (which
	 * differs from the temporary cache key).
	 */
	public UUID finalizePdf(UUID cacheKey) throws IOException {
		CachedPdf cached = pdfCache.remove(cacheKey);
		if (cached == null) {
			throw new RuntimeException("Cached PDF not found for key: " + cacheKey);
		}

		Path storagePath = Paths.get(pdfStoragePath);
		Files.createDirectories(storagePath);

		// Use a fresh UUID prefix to avoid filename collisions on disk
		UUID fileUuid = UUID.randomUUID();
		String storedFilename = fileUuid + "_" + sanitizeFilename(cached.originalFilename);
		Path filePath = storagePath.resolve(storedFilename);
		Files.write(filePath, cached.content);

		PDFDocument document = new PDFDocument();
		// ID is auto-generated by JPA
		document.setFilename(cached.originalFilename);
		document.setFilePath(filePath.toString());
		document.setFileSize((long) cached.content.length);
		document.setExtractedFields(cached.extractedFields);
		document.setConfidenceScore(cached.confidenceScore);
		document.setExtractionQuality(cached.extractionQuality);
		document.setType(com.learnhub.activitymanagement.entity.enums.DocumentType.SOURCE_PDF);
		document.setCreatedAt(LocalDateTime.now());

		document = pdfDocumentRepository.save(document);
		UUID documentId = document.getId();
		logger.info("PDF finalized: cacheKey={}, documentId={}, storedAs={}", cacheKey, documentId, storedFilename);
		return documentId;
	}

	/**
	 * Retrieve PDF content – checks the in-memory cache first, then the database /
	 * filesystem.
	 */
	public byte[] getPdfContent(UUID documentId) throws IOException {
		CachedPdf cached = pdfCache.get(documentId);
		if (cached != null) {
			return cached.content;
		}

		PDFDocument document = pdfDocumentRepository.findById(documentId)
				.orElseThrow(() -> new RuntimeException("PDF document not found"));

		Path filePath = Paths.get(document.getFilePath());
		if (!Files.exists(filePath)) {
			throw new RuntimeException("PDF file not found on filesystem");
		}

		return Files.readAllBytes(filePath);
	}

	/**
	 * Retrieve PDF document metadata – checks the in-memory cache first, then the
	 * database.
	 */
	public PDFDocument getPdfDocument(UUID documentId) {
		CachedPdf cached = pdfCache.get(documentId);
		if (cached != null) {
			PDFDocument transientDoc = new PDFDocument();
			transientDoc.setId(documentId);
			transientDoc.setFilename(cached.originalFilename);
			transientDoc.setFileSize((long) cached.content.length);
			transientDoc.setExtractedFields(cached.extractedFields);
			transientDoc.setConfidenceScore(cached.confidenceScore);
			transientDoc.setExtractionQuality(cached.extractionQuality);
			transientDoc.setCreatedAt(cached.uploadedAt);
			return transientDoc;
		}

		return pdfDocumentRepository.findById(documentId)
				.orElseThrow(() -> new RuntimeException("PDF document not found"));
	}

	/**
	 * Update extraction results – updates the cache entry if the PDF has not been
	 * finalized yet, otherwise updates the database record.
	 */
	public void updatePdfExtractionResults(UUID documentId, Map<String, Object> extractedFields, String confidenceScore,
			String extractionQuality) {
		String json;
		try {
			json = extractedFields != null ? OBJECT_MAPPER.writeValueAsString(extractedFields) : "{}";
		} catch (Exception e) {
			throw new RuntimeException("Failed to serialize extracted fields to JSON", e);
		}

		CachedPdf cached = pdfCache.get(documentId);
		if (cached != null) {
			cached.extractedFields = json;
			cached.confidenceScore = confidenceScore;
			cached.extractionQuality = extractionQuality;
			return;
		}

		PDFDocument document = pdfDocumentRepository.findById(documentId)
				.orElseThrow(() -> new RuntimeException("PDF document not found"));
		document.setExtractedFields(json);
		document.setConfidenceScore(confidenceScore);
		document.setExtractionQuality(extractionQuality);

		pdfDocumentRepository.save(document);
	}

	/**
	 * Periodically evict expired cache entries (older than
	 * {@link #CACHE_TTL_MINUTES}).
	 */
	@Scheduled(fixedRate = 300_000) // every 5 minutes
	public void evictExpiredCacheEntries() {
		LocalDateTime cutoff = LocalDateTime.now().minusMinutes(CACHE_TTL_MINUTES);
		int before = pdfCache.size();
		pdfCache.entrySet().removeIf(entry -> entry.getValue().uploadedAt.isBefore(cutoff));
		int evicted = before - pdfCache.size();
		if (evicted > 0) {
			logger.info("Evicted {} expired PDF cache entries, {} remaining", evicted, pdfCache.size());
		}
	}

	private void evictOldestCacheEntry() {
		pdfCache.entrySet().stream().min(Comparator.comparing(e -> e.getValue().uploadedAt)).ifPresent(oldest -> {
			pdfCache.remove(oldest.getKey());
			logger.info("Evicted oldest PDF cache entry key={} to stay under max size", oldest.getKey());
		});
	}

	/**
	 * Sanitize a filename to prevent path traversal and keep only safe characters.
	 */
	private String sanitizeFilename(String filename) {
		if (filename == null || filename.isBlank()) {
			return "document.pdf";
		}
		// Remove path separators and keep only safe characters
		String sanitized = Paths.get(filename).getFileName().toString();
		sanitized = sanitized.replaceAll("[^a-zA-Z0-9._-]", "_");
		if (sanitized.isEmpty()) {
			return "document.pdf";
		}
		return sanitized;
	}

	// Visible for testing
	ConcurrentHashMap<UUID, CachedPdf> getPdfCache() {
		return pdfCache;
	}

	public LessonPlanInfoResponse getLessonPlanInfo(List<Map<String, Object>> activities) {
		int availablePdfs = 0;
		List<Integer> missingPdfs = new ArrayList<>();

		for (int i = 0; i < activities.size(); i++) {
			Map<String, Object> activity = activities.get(i);
			Object docIdObj = activity.get("documentId");

			if (docIdObj != null) {
				try {
					UUID documentId = UUID.fromString(docIdObj.toString());
					byte[] content = getPdfContent(documentId);
					if (content != null && content.length > 0) {
						availablePdfs++;
					} else {
						missingPdfs.add(i);
					}
				} catch (IllegalArgumentException e) {
					// Invalid UUID format
					missingPdfs.add(i);
				} catch (Exception e) {
					missingPdfs.add(i);
				}
			} else {
				missingPdfs.add(i);
			}
		}

		boolean canGenerate = missingPdfs.isEmpty();
		return new LessonPlanInfoResponse(canGenerate, availablePdfs, missingPdfs);
	}

	public byte[] generateLessonPlan(List<Map<String, Object>> activities, Map<String, Object> searchCriteria,
			List<Map<String, Object>> breaks, Integer totalDuration) throws IOException {
		/**
		 * Generate a complete lesson plan PDF matching Flask implementation: 1.
		 * Generate summary/cover page with search criteria, activities list, breaks 2.
		 * Get activity PDFs based on activity_documents table 3. Merge summary page +
		 * activity PDFs using PDFBox
		 */

		if (activities == null || activities.isEmpty()) {
			throw new RuntimeException("No activities provided for lesson plan");
		}

		try {
			// 1. Generate summary page
			byte[] summaryPdf = generateSummaryPage(activities, searchCriteria, breaks, totalDuration);
			logger.debug("Generated summary page for lesson plan PDF.");
			// 2. Get activity PDFs
			List<byte[]> activityPdfs = getActivityPdfs(activities);
			logger.debug("Retrieved {} activity PDFs for lesson plan.", activityPdfs.size());
			// 3. Merge all PDFs
			return mergePdfs(summaryPdf, activityPdfs);

		} catch (Exception e) {
			e.printStackTrace();
			logger.error("Error generating lesson plan PDF: {}", e.toString());
			throw new IOException("Failed to generate lesson plan: " + e.getMessage(), e);
		}
	}

	private List<byte[]> getActivityPdfs(List<Map<String, Object>> activities) {
		List<byte[]> pdfs = new ArrayList<>();

		for (Map<String, Object> activityMap : activities) {
			try {
				// Extract activity ID
				Object idObj = activityMap.get("id");
				if (idObj == null)
					continue;

				UUID activityId;
				try {
					activityId = UUID.fromString(idObj.toString());
				} catch (IllegalArgumentException e) {
					// Invalid UUID format, skip this activity
					continue;
				}

				// Get activity from database
				Activity activity = activityRepository.findById(activityId).orElse(null);
				if (activity == null)
					continue;

				byte[] pdfContent = null;

				// Try to get PDF via the first SOURCE_PDF document
				UUID docId = activity.getDocuments().stream().filter(
						d -> d.getType() == com.learnhub.activitymanagement.entity.enums.DocumentType.SOURCE_PDF)
						.findFirst().map(com.learnhub.documentmanagement.entity.PDFDocument::getId).orElse(null);
				if (docId != null) {
					try {
						pdfContent = getPdfContent(docId);
					} catch (Exception e) {
						// PDF not available for this activity
					}
				}

				if (pdfContent != null && pdfContent.length > 0) {
					pdfs.add(pdfContent);
				}

			} catch (Exception e) {
				// Skip this activity if any error
				continue;
			}
		}

		return pdfs;
	}

	private byte[] mergePdfs(byte[] summaryPdf, List<byte[]> activityPdfs) throws IOException {
		try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
				PdfDocument mergedPdf = new PdfDocument(new PdfWriter(outputStream))) {
			appendDocumentPages(mergedPdf, summaryPdf);

			for (byte[] activityPdf : activityPdfs) {
				if (activityPdf != null && activityPdf.length > 0) {
					appendDocumentPages(mergedPdf, activityPdf);
				}
			}

			mergedPdf.close();
			return outputStream.toByteArray();
		}
	}

	private void appendDocumentPages(PdfDocument target, byte[] sourceBytes) throws IOException {
		try (PdfDocument source = new PdfDocument(new PdfReader(new java.io.ByteArrayInputStream(sourceBytes)))) {
			new PdfMerger(target).merge(source, 1, source.getNumberOfPages());
		}
	}

	private byte[] generateSummaryPage(List<Map<String, Object>> activities, Map<String, Object> searchCriteria,
			List<Map<String, Object>> breaks, Integer totalDuration) throws IOException {
		try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
				PdfDocument pdfDocument = new PdfDocument(new PdfWriter(outputStream));
				Document document = new Document(pdfDocument, PageSize.A4)) {
			document.setMargins(50, 50, 50, 50);

			document.add(new Paragraph("Lesson Plan Summary").setBold().setFontSize(18)
					.setTextAlignment(TextAlignment.CENTER).setMarginBottom(24));

			document.add(buildSectionHeader("Search Criteria:"));
			if (searchCriteria != null && !searchCriteria.isEmpty()) {
				List<String[]> criteriaRows = new ArrayList<>();
				for (Map.Entry<String, Object> entry : searchCriteria.entrySet()) {
					if (entry.getValue() != null && !entry.getValue().toString().isEmpty()) {
						String key = entry.getKey().replace("_", " ");
						key = key.substring(0, 1).toUpperCase() + key.substring(1);
						criteriaRows.add(new String[]{key, entry.getValue().toString()});
					}
				}
				if (!criteriaRows.isEmpty()) {
					document.add(buildTable(new float[]{150f, 350f}, criteriaRows, false));
				}
			}

			document.add(buildSectionHeader("Activities:"));
			List<String[]> activityRows = new ArrayList<>();
			activityRows.add(new String[]{"#", "Name", "Duration", "Format", "Bloom Level"});
			int activityNum = 1;
			for (Map<String, Object> activity : activities) {
				String name = activity.getOrDefault("name", "N/A").toString();
				Object durationObj = activity.get("durationMinMinutes");
				String duration = durationObj != null ? durationObj.toString() + " min" : "N/A";
				String format = activity.getOrDefault("format", "N/A").toString();
				String bloomLevel = activity.getOrDefault("bloom_level", "N/A").toString();
				activityRows.add(new String[]{String.valueOf(activityNum++), name, duration, format, bloomLevel});
			}
			document.add(buildTable(new float[]{30f, 200f, 80f, 80f, 110f}, activityRows, true));

			if (breaks != null && !breaks.isEmpty()) {
				document.add(buildSectionHeader("Breaks:"));
				List<String[]> breakRows = new ArrayList<>();
				breakRows.add(new String[]{"Duration", "Description"});
				for (Map<String, Object> breakItem : breaks) {
					Object durationObj = breakItem.get("duration");
					String duration = durationObj != null ? durationObj.toString() + " min" : "N/A";
					String description = breakItem.getOrDefault("description", "Break").toString();
					breakRows.add(new String[]{duration, description});
				}
				document.add(buildTable(new float[]{100f, 400f}, breakRows, true));
			}

			document.add(buildSectionHeader(
					"Total Duration: " + (totalDuration != null ? totalDuration : 0) + " minutes"));
			String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
			document.add(new Paragraph("Generated: " + timestamp).setFontSize(10).setMarginTop(12));

			document.close();
			return outputStream.toByteArray();
		}
	}

	private Paragraph buildSectionHeader(String text) {
		return new Paragraph(text).setBold().setFontSize(12).setMarginTop(18).setMarginBottom(8);
	}

	private Table buildTable(float[] columnWidths, List<String[]> rows, boolean hasHeader) {
		Table table = new Table(columnWidths);
		table.useAllAvailableWidth();

		for (int rowIdx = 0; rowIdx < rows.size(); rowIdx++) {
			String[] row = rows.get(rowIdx);
			boolean isHeader = hasHeader && rowIdx == 0;
			for (String value : row) {
				String cellText = value == null ? "" : value;
				if (cellText.length() > 40) {
					cellText = cellText.substring(0, 37) + "...";
				}

				Cell cell = new Cell().add(new Paragraph(cellText).setFontSize(10)).setPadding(5);
				if (isHeader) {
					cell.setBold().setBackgroundColor(ColorConstants.LIGHT_GRAY);
				}
				table.addCell(cell);
			}
		}

		return table;
	}

	/**
	 * Extract text from a cached or persisted PDF identified by its ID/cache key.
	 */
	public String extractTextFromPdf(UUID documentIdOrCacheKey) {
		try {
			byte[] pdfContent;

			// First try the in-memory cache
			CachedPdf cached = pdfCache.get(documentIdOrCacheKey);
			if (cached != null) {
				pdfContent = cached.content;
			} else {
				// Fall back to persisted PDF
				pdfContent = getPdfContent(documentIdOrCacheKey);
			}
			try (PdfDocument document = new PdfDocument(new PdfReader(new java.io.ByteArrayInputStream(pdfContent)))) {
				StringBuilder extractedText = new StringBuilder();
				for (int pageNumber = 1; pageNumber <= document.getNumberOfPages(); pageNumber++) {
					extractedText.append(PdfTextExtractor.getTextFromPage(document.getPage(pageNumber)));
					extractedText.append(System.lineSeparator());
				}
				return extractedText.toString();
			}
		} catch (Exception e) {
			logger.error("Failed to extract text from PDF {}: {}", documentIdOrCacheKey, e.getMessage());
			throw new RuntimeException("Failed to extract text from PDF: " + e.getMessage(), e);
		}
	}
}
