package com.learnhub.documentmanagement.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.itextpdf.html2pdf.HtmlConverter;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.parser.PdfTextExtractor;
import com.itextpdf.kernel.utils.PdfMerger;
import com.learnhub.activitymanagement.dto.response.LessonPlanInfoResponse;
import com.learnhub.activitymanagement.entity.Activity;
import com.learnhub.activitymanagement.entity.ActivityMarkdown;
import com.learnhub.activitymanagement.entity.enums.MarkdownType;
import com.learnhub.activitymanagement.repository.ActivityRepository;
import com.learnhub.documentmanagement.entity.PDFDocument;
import com.learnhub.documentmanagement.repository.PDFDocumentRepository;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ClassPathResource;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

@Service
public class PDFService {

	private static final Logger logger = LoggerFactory.getLogger(PDFService.class);
	private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
	private static final int MAX_CACHE_SIZE = 100;
	private static final long CACHE_TTL_MINUTES = 60;
	private static final String LESSON_PLAN_COVER_TEMPLATE_PATH = "templates/markdown/lesson-plan-cover.html";
	private static final String[] MARKDOWN_TYPE_ORDER = {"deckblatt", "artikulationsschema", "hintergrundwissen"};

	@Autowired
	private PDFDocumentRepository pdfDocumentRepository;

	@Autowired
	private ActivityRepository activityRepository;

	@Autowired
	private LLMService llmService;

	@Autowired
	private MarkdownToHtmlService markdownToHtmlService;

	@Autowired
	private MarkdownToPdfService markdownToPdfService;

	@Value("${pdf.storage.path:/app/data/pdfs}")
	private String pdfStoragePath;

	private final ConcurrentHashMap<UUID, CachedPdf> pdfCache = new ConcurrentHashMap<>();

	/**
	 * In-memory representation of a PDF that has been uploaded but not yet
	 * persisted.
	 */
	static class CachedPdf {

		final byte[] content;
		final String originalFilename;
		final LocalDateTime uploadedAt;
		String extractedFields = "{}";
		String confidenceScore;
		String extractionQuality;

		CachedPdf(byte[] content, String originalFilename) {
			this.content = content;
			this.originalFilename = originalFilename;
			this.uploadedAt = LocalDateTime.now();
		}
	}

	/**
	 * Cache PDF in memory without persisting to filesystem or database. Returns a
	 * UUID key that can later be passed to {@link #finalizePdf(UUID)} when the
	 * connected activity is created.
	 */
	public UUID cachePdf(byte[] pdfContent, String filename) {
		if (pdfCache.size() >= MAX_CACHE_SIZE) {
			evictOldestCacheEntry();
		}

		UUID cacheKey = UUID.randomUUID();
		pdfCache.put(cacheKey, new CachedPdf(pdfContent, filename));
		logger.debug("PDF cached with key={}, originalFilename={}", cacheKey, filename);
		return cacheKey;
	}

	/**
	 * Persist a previously cached PDF to the filesystem and database. JPA
	 * auto-generates the document ID. Returns the generated document ID (which
	 * differs from the temporary cache key).
	 */
	public UUID finalizePdf(UUID cacheKey) throws IOException {
		CachedPdf cached = pdfCache.remove(cacheKey);
		if (cached == null) {
			throw new RuntimeException("Cached PDF not found for key: " + cacheKey);
		}

		Path storagePath = Paths.get(pdfStoragePath);
		Files.createDirectories(storagePath);

		// Use a fresh UUID prefix to avoid filename collisions on disk
		UUID fileUuid = UUID.randomUUID();
		String storedFilename = fileUuid + "_" + sanitizeFilename(cached.originalFilename);
		Path filePath = storagePath.resolve(storedFilename);
		Files.write(filePath, cached.content);

		PDFDocument document = new PDFDocument();
		// ID is auto-generated by JPA
		document.setFilename(cached.originalFilename);
		document.setFilePath(filePath.toString());
		document.setFileSize((long) cached.content.length);
		document.setExtractedFields(cached.extractedFields);
		document.setConfidenceScore(cached.confidenceScore);
		document.setExtractionQuality(cached.extractionQuality);
		document.setType(com.learnhub.activitymanagement.entity.enums.DocumentType.SOURCE_PDF);
		document.setCreatedAt(LocalDateTime.now());

		document = pdfDocumentRepository.save(document);
		UUID documentId = document.getId();
		logger.info("PDF finalized: cacheKey={}, documentId={}, storedAs={}", cacheKey, documentId, storedFilename);
		return documentId;
	}

	/**
	 * Retrieve PDF content – checks the in-memory cache first, then the database /
	 * filesystem.
	 */
	public byte[] getPdfContent(UUID documentId) throws IOException {
		CachedPdf cached = pdfCache.get(documentId);
		if (cached != null) {
			return cached.content;
		}

		PDFDocument document = pdfDocumentRepository.findById(documentId)
				.orElseThrow(() -> new RuntimeException("PDF document not found"));

		Path filePath = resolveReadableFilePath(document.getFilePath());

		return Files.readAllBytes(filePath);
	}

	/**
	 * Retrieve PDF document metadata – checks the in-memory cache first, then the
	 * database.
	 */
	public PDFDocument getPdfDocument(UUID documentId) {
		CachedPdf cached = pdfCache.get(documentId);
		if (cached != null) {
			PDFDocument transientDoc = new PDFDocument();
			transientDoc.setId(documentId);
			transientDoc.setFilename(cached.originalFilename);
			transientDoc.setFileSize((long) cached.content.length);
			transientDoc.setExtractedFields(cached.extractedFields);
			transientDoc.setConfidenceScore(cached.confidenceScore);
			transientDoc.setExtractionQuality(cached.extractionQuality);
			transientDoc.setCreatedAt(cached.uploadedAt);
			return transientDoc;
		}

		return pdfDocumentRepository.findById(documentId)
				.orElseThrow(() -> new RuntimeException("PDF document not found"));
	}

	private Path resolveReadableFilePath(String storedFilePath) {
		Path filePath = Paths.get(storedFilePath);
		if (Files.exists(filePath)) {
			return filePath;
		}

		Path fallbackPath = Paths.get(pdfStoragePath).resolve(filePath.getFileName().toString());
		if (Files.exists(fallbackPath)) {
			logger.info("PDF file missing at stored path {}. Using current PDF storage path {}", storedFilePath,
					fallbackPath);
			return fallbackPath;
		}

		throw new RuntimeException("PDF file not found on filesystem");
	}

	/**
	 * Update extraction results – updates the cache entry if the PDF has not been
	 * finalized yet, otherwise updates the database record.
	 */
	public void updatePdfExtractionResults(UUID documentId, Map<String, Object> extractedFields, String confidenceScore,
			String extractionQuality) {
		String json;
		try {
			json = extractedFields != null ? OBJECT_MAPPER.writeValueAsString(extractedFields) : "{}";
		} catch (Exception e) {
			throw new RuntimeException("Failed to serialize extracted fields to JSON", e);
		}

		CachedPdf cached = pdfCache.get(documentId);
		if (cached != null) {
			cached.extractedFields = json;
			cached.confidenceScore = confidenceScore;
			cached.extractionQuality = extractionQuality;
			return;
		}

		PDFDocument document = pdfDocumentRepository.findById(documentId)
				.orElseThrow(() -> new RuntimeException("PDF document not found"));
		document.setExtractedFields(json);
		document.setConfidenceScore(confidenceScore);
		document.setExtractionQuality(extractionQuality);

		pdfDocumentRepository.save(document);
	}

	/**
	 * Periodically evict expired cache entries (older than
	 * {@link #CACHE_TTL_MINUTES}).
	 */
	@Scheduled(fixedRate = 300_000) // every 5 minutes
	public void evictExpiredCacheEntries() {
		LocalDateTime cutoff = LocalDateTime.now().minusMinutes(CACHE_TTL_MINUTES);
		int before = pdfCache.size();
		pdfCache.entrySet().removeIf(entry -> entry.getValue().uploadedAt.isBefore(cutoff));
		int evicted = before - pdfCache.size();
		if (evicted > 0) {
			logger.info("Evicted {} expired PDF cache entries, {} remaining", evicted, pdfCache.size());
		}
	}

	private void evictOldestCacheEntry() {
		pdfCache.entrySet().stream().min(Comparator.comparing(e -> e.getValue().uploadedAt)).ifPresent(oldest -> {
			pdfCache.remove(oldest.getKey());
			logger.info("Evicted oldest PDF cache entry key={} to stay under max size", oldest.getKey());
		});
	}

	/**
	 * Sanitize a filename to prevent path traversal and keep only safe characters.
	 */
	private String sanitizeFilename(String filename) {
		if (filename == null || filename.isBlank()) {
			return "document.pdf";
		}
		// Remove path separators and keep only safe characters
		String sanitized = Paths.get(filename).getFileName().toString();
		sanitized = sanitized.replaceAll("[^a-zA-Z0-9._-]", "_");
		if (sanitized.isEmpty()) {
			return "document.pdf";
		}
		return sanitized;
	}

	// Visible for testing
	ConcurrentHashMap<UUID, CachedPdf> getPdfCache() {
		return pdfCache;
	}

	public LessonPlanInfoResponse getLessonPlanInfo(List<Map<String, Object>> activities) {
		int availablePdfs = 0;
		List<Integer> missingPdfs = new ArrayList<>();

		for (int i = 0; i < activities.size(); i++) {
			Map<String, Object> activity = activities.get(i);
			if (hasLessonPlanMarkdowns(activity)) {
				availablePdfs++;
			} else {
				missingPdfs.add(i);
			}
		}

		boolean canGenerate = missingPdfs.isEmpty();
		return new LessonPlanInfoResponse(canGenerate, availablePdfs, missingPdfs);
	}

	/**
	 * Returns true if the activity has at least one markdown available for
	 * lesson-plan PDF generation.
	 */
	private boolean hasLessonPlanMarkdowns(Map<String, Object> activityMap) {
		// 1. Check markdowns embedded directly in the request map
		if (requestMapHasMarkdowns(activityMap)) {
			return true;
		}

		// 2. Check DB for persisted markdowns
		UUID activityId = parseUuid(activityMap.get("id"));
		if (activityId != null) {
			Activity activity = activityRepository.findById(activityId).orElse(null);
			if (activity != null) {
				return activity.getMarkdowns() != null && !activity.getMarkdowns().isEmpty();
			}
		}

		return false;
	}

	/**
	 * Returns true if the activity map contains at least one markdown entry with
	 * non-empty content.
	 */
	private boolean requestMapHasMarkdowns(Map<String, Object> activityMap) {
		Object markdownsObj = activityMap.get("markdowns");
		if (!(markdownsObj instanceof List<?> markdownsList)) {
			return false;
		}
		for (Object mdObj : markdownsList) {
			if (!(mdObj instanceof Map<?, ?> mdMap)) {
				continue;
			}
			Object contentObj = mdMap.get("content");
			if (contentObj != null && !contentObj.toString().trim().isEmpty()) {
				return true;
			}
		}
		return false;
	}

	private UUID parseUuid(Object value) {
		if (value == null) {
			return null;
		}

		try {
			return UUID.fromString(value.toString());
		} catch (IllegalArgumentException e) {
			return null;
		}
	}

	public byte[] generateLessonPlan(List<Map<String, Object>> activities, Map<String, Object> searchCriteria,
			List<Map<String, Object>> breaks, Integer totalDuration) throws IOException {
		/**
		 * Generate a complete lesson plan PDF matching Flask implementation: 1.
		 * Generate summary/cover page with search criteria, activities list, breaks 2.
		 * Get activity PDFs based on activity_documents table 3. Merge summary page +
		 * activity PDFs using PDFBox
		 */

		if (activities == null || activities.isEmpty()) {
			throw new RuntimeException("No activities provided for lesson plan");
		}

		try {
			// 1. Generate summary page
			byte[] summaryPdf = generateSummaryPage(activities, searchCriteria, breaks, totalDuration);
			logger.debug("Generated summary page for lesson plan PDF.");
			// 2. Get activity PDFs
			List<byte[]> activityPdfs = getActivityPdfs(activities);
			logger.debug("Retrieved {} activity PDFs for lesson plan.", activityPdfs.size());
			// 3. Merge all PDFs
			return mergePdfs(summaryPdf, activityPdfs);

		} catch (Exception e) {
			e.printStackTrace();
			logger.error("Error generating lesson plan PDF: {}", e.toString());
			throw new IOException("Failed to generate lesson plan: " + e.getMessage(), e);
		}
	}

	private List<byte[]> getActivityPdfs(List<Map<String, Object>> activities) throws IOException {
		List<byte[]> pdfs = new ArrayList<>();

		for (Map<String, Object> activityMap : activities) {
			String activityName = activityMap.getOrDefault("name", "").toString();

			// 1. Use markdown content from the request map (fastest – already in memory)
			List<byte[]> markdownPdfs = generatePdfsFromRequestMarkdowns(activityMap, activityName);

			// 2. If request didn't carry markdowns, look them up in the DB
			if (markdownPdfs.isEmpty()) {
				UUID activityId = parseUuid(activityMap.get("id"));
				if (activityId != null) {
					Activity dbActivity = activityRepository.findById(activityId).orElse(null);
					if (dbActivity != null) {
						markdownPdfs = generatePdfsFromMarkdowns(dbActivity);
					}
				}
			}

			if (markdownPdfs.isEmpty()) {
				throw new IllegalArgumentException(
						"No markdown content available for lesson plan activity: " + activityName);
			}

			byte[] merged = markdownPdfs.size() == 1 ? markdownPdfs.get(0) : mergeList(markdownPdfs);
			pdfs.add(merged);
		}

		return pdfs;
	}

	/**
	 * Render PDFs from markdown sections carried inside the request activity map.
	 * The map is expected to contain a {@code markdowns} key with a list of objects
	 * each having {@code type}, {@code content}, and optionally {@code landscape}.
	 */
	private List<byte[]> generatePdfsFromRequestMarkdowns(Map<String, Object> activityMap, String activityName) {
		List<byte[]> parts = new ArrayList<>();
		Object markdownsObj = activityMap.get("markdowns");
		if (!(markdownsObj instanceof List<?> markdownsList) || markdownsList.isEmpty()) {
			return parts;
		}
		for (String typeName : MARKDOWN_TYPE_ORDER) {
			for (Object mdObj : markdownsList) {
				if (!(mdObj instanceof Map<?, ?> mdMap)) {
					continue;
				}
				Object typeObj = mdMap.get("type");
				if (typeObj == null || !typeName.equalsIgnoreCase(typeObj.toString())) {
					continue;
				}
				Object contentObj = mdMap.get("content");
				if (contentObj == null || contentObj.toString().trim().isEmpty()) {
					continue;
				}
				Object landscapeObj = mdMap.get("landscape");
				boolean landscape = landscapeObj instanceof Boolean ? (Boolean) landscapeObj : false;
				try {
					parts.add(markdownToPdfService.renderMarkdownToPdf(contentObj.toString(), landscape, activityName));
				} catch (Exception e) {
					logger.warn("Failed to render markdown PDF from request for type {}: {}", typeName, e.getMessage());
				}
			}
		}
		return parts;
	}

	/**
	 * Render PDFs for each markdown section (deckblatt, artikulationsschema,
	 * hintergrundwissen) of the given activity in their stored order.
	 */
	private List<byte[]> generatePdfsFromMarkdowns(Activity activity) {
		List<byte[]> parts = new ArrayList<>();
		if (activity.getMarkdowns() == null || activity.getMarkdowns().isEmpty()) {
			return parts;
		}
		String activityName = activity.getName() != null ? activity.getName() : "";
		for (String typeName : MARKDOWN_TYPE_ORDER) {
			MarkdownType type;
			try {
				type = MarkdownType.fromValue(typeName);
			} catch (IllegalArgumentException e) {
				continue;
			}
			for (ActivityMarkdown md : activity.getMarkdowns()) {
				if (md.getType() == type && md.getContent() != null && !md.getContent().trim().isEmpty()) {
					try {
						parts.add(markdownToPdfService.renderMarkdownToPdf(md.getContent(), md.isLandscape(),
								activityName));
					} catch (Exception e) {
						logger.warn("Failed to render markdown PDF for activity {}, type {}: {}", activity.getId(),
								typeName, e.getMessage());
					}
				}
			}
		}
		return parts;
	}

	private byte[] mergeList(List<byte[]> pdfParts) throws IOException {
		try (ByteArrayOutputStream baos = new ByteArrayOutputStream();
				PdfDocument mergedDoc = new PdfDocument(new PdfWriter(baos))) {
			PdfMerger merger = new PdfMerger(mergedDoc);
			for (byte[] part : pdfParts) {
				try (PdfDocument src = new PdfDocument(new PdfReader(new ByteArrayInputStream(part)))) {
					merger.merge(src, 1, src.getNumberOfPages());
				}
			}
			mergedDoc.close();
			return baos.toByteArray();
		}
	}

	private byte[] mergePdfs(byte[] summaryPdf, List<byte[]> activityPdfs) throws IOException {
		try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
				PdfDocument mergedPdf = new PdfDocument(new PdfWriter(outputStream))) {
			appendDocumentPages(mergedPdf, summaryPdf);

			for (byte[] activityPdf : activityPdfs) {
				if (activityPdf != null && activityPdf.length > 0) {
					appendDocumentPages(mergedPdf, activityPdf);
				}
			}

			mergedPdf.close();
			return outputStream.toByteArray();
		}
	}

	private void appendDocumentPages(PdfDocument target, byte[] sourceBytes) throws IOException {
		try (PdfDocument source = new PdfDocument(new PdfReader(new ByteArrayInputStream(sourceBytes)))) {
			new PdfMerger(target).merge(source, 1, source.getNumberOfPages());
		}
	}

	/**
	 * Generate the cover / table-of-contents page for the lesson plan PDF using an
	 * HTML template populated with the supplied activity and break data.
	 */
	private byte[] generateSummaryPage(List<Map<String, Object>> activities, Map<String, Object> searchCriteria,
			List<Map<String, Object>> breaks, Integer totalDuration) throws IOException {
		String template = loadCoverTemplate();

		// Activities table rows
		StringBuilder activityRows = new StringBuilder();
		int num = 1;
		for (Map<String, Object> activity : activities) {
			String name = escapeHtml(activity.getOrDefault("name", "N/A").toString());
			Object durationObj = activity.get("durationMinMinutes");
			String duration = durationObj != null ? durationObj.toString() + " min" : "N/A";
			String format = escapeHtml(activity.getOrDefault("format", "N/A").toString());
			String bloomLevel = escapeHtml(
					activity.getOrDefault("bloomLevel", activity.getOrDefault("bloom_level", "N/A")).toString());
			activityRows.append("<tr>")
					.append("<td class=\"num-col\">").append(num++).append("</td>")
					.append("<td>").append(name).append("</td>")
					.append("<td class=\"duration-col\">").append(duration).append("</td>")
					.append("<td class=\"format-col\">").append(format).append("</td>")
					.append("<td class=\"bloom-col\">").append(bloomLevel).append("</td>")
					.append("</tr>\n");
		}

		// Search criteria section (optional)
		String searchCriteriaSection = "";
		if (searchCriteria != null && !searchCriteria.isEmpty()) {
			StringBuilder sb = new StringBuilder();
			sb.append("<h2>Suchkriterien</h2>\n<table>\n<tbody>\n");
			for (Map.Entry<String, Object> entry : searchCriteria.entrySet()) {
				if (entry.getValue() != null && !entry.getValue().toString().isEmpty()) {
					String key = entry.getKey().replace("_", " ");
					key = key.substring(0, 1).toUpperCase() + key.substring(1);
					sb.append("<tr>")
							.append("<td class=\"criteria-key\">").append(escapeHtml(key)).append("</td>")
							.append("<td>").append(escapeHtml(entry.getValue().toString())).append("</td>")
							.append("</tr>\n");
				}
			}
			sb.append("</tbody>\n</table>\n");
			searchCriteriaSection = sb.toString();
		}

		// Breaks section (optional)
		String breaksSection = "";
		if (breaks != null && !breaks.isEmpty()) {
			StringBuilder sb = new StringBuilder();
			sb.append("<h2>Pausen</h2>\n<table>\n");
			sb.append("<thead><tr>")
					.append("<th style=\"width:80pt\">Dauer</th>")
					.append("<th>Beschreibung</th>")
					.append("</tr></thead>\n<tbody>\n");
			for (Map<String, Object> breakItem : breaks) {
				Object durationObj = breakItem.get("duration");
				String duration = durationObj != null ? durationObj.toString() + " min" : "N/A";
				String description = escapeHtml(breakItem.getOrDefault("description", "Pause").toString());
				sb.append("<tr>")
						.append("<td>").append(duration).append("</td>")
						.append("<td>").append(description).append("</td>")
						.append("</tr>\n");
			}
			sb.append("</tbody>\n</table>\n");
			breaksSection = sb.toString();
		}

		String downloadDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd.MM.yyyy HH:mm"));
		String totalDurationStr = totalDuration != null ? totalDuration.toString() : "0";
		String activityCount = String.valueOf(activities.size());
		String logoDataUri = markdownToHtmlService.getLogoDataUri();

		String html = template
				.replace("{{logoDataUri}}", logoDataUri)
				.replace("{{downloadDate}}", downloadDate)
				.replace("{{totalDuration}}", totalDurationStr)
				.replace("{{activityCount}}", activityCount)
				.replace("{{activitiesTableRows}}", activityRows.toString())
				.replace("{{searchCriteriaSection}}", searchCriteriaSection)
				.replace("{{breaksSection}}", breaksSection);

		try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
			HtmlConverter.convertToPdf(html, baos);
			return baos.toByteArray();
		}
	}

	private String loadCoverTemplate() {
		ClassPathResource resource = new ClassPathResource(LESSON_PLAN_COVER_TEMPLATE_PATH);
		try (InputStream in = resource.getInputStream()) {
			return new String(in.readAllBytes(), StandardCharsets.UTF_8);
		} catch (IOException e) {
			throw new IllegalStateException("Failed to load lesson-plan-cover template", e);
		}
	}

	private static String escapeHtml(String text) {
		if (text == null) {
			return "";
		}
		return text.replace("&", "&amp;")
				.replace("<", "&lt;")
				.replace(">", "&gt;")
				.replace("\"", "&quot;")
				.replace("'", "&#39;");
	}

	/**
	 * Extract text from a cached or persisted PDF identified by its ID/cache key.
	 */
	public String extractTextFromPdf(UUID documentIdOrCacheKey) {
		try {
			byte[] pdfContent;

			// First try the in-memory cache
			CachedPdf cached = pdfCache.get(documentIdOrCacheKey);
			if (cached != null) {
				pdfContent = cached.content;
			} else {
				// Fall back to persisted PDF
				pdfContent = getPdfContent(documentIdOrCacheKey);
			}
			try (PdfDocument document = new PdfDocument(new PdfReader(new ByteArrayInputStream(pdfContent)))) {
				StringBuilder extractedText = new StringBuilder();
				for (int pageNumber = 1; pageNumber <= document.getNumberOfPages(); pageNumber++) {
					extractedText.append(PdfTextExtractor.getTextFromPage(document.getPage(pageNumber)));
					extractedText.append(System.lineSeparator());
				}
				return extractedText.toString();
			}
		} catch (Exception e) {
			logger.error("Failed to extract text from PDF {}: {}", documentIdOrCacheKey, e.getMessage());
			throw new RuntimeException("Failed to extract text from PDF: " + e.getMessage(), e);
		}
	}
}
