name: Build and Push Client Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/build-client.yml"
  workflow_dispatch:

concurrency:
  group: build-client-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-client:
    permissions:
      contents: read
      packages: write
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ls1intum/learn-hub/client
      docker-file: client/Dockerfile
      docker-context: ./client
      tags: |
        type=sha,format=short,prefix=main-
        latest
    secrets: inherit
