name: Build and Push Docker Images

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "MIGRATION.md"
      - "LICENSE"
      - "docs/**"
      - "website/**"
      - "dataset/**"
      - ".github/**"
      - "!.github/workflows/build.yml"
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "README.md"
      - "MIGRATION.md"
      - "LICENSE"
      - "docs/**"
      - "website/**"
      - "dataset/**"
      - ".github/**"
      - "!.github/workflows/build.yml"
  release:
    types:
      - created

jobs:
  build:
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-name: ls1intum/learn-hub/client
            docker-file: client/Dockerfile
            docker-context: ./client
          - image-name: ls1intum/learn-hub/spring-server
            docker-file: server-spring/Dockerfile
            docker-context: ./server-spring
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ${{ matrix.image-name }}
      docker-file: ${{ matrix.docker-file }}
      docker-context: ${{ matrix.docker-context }}
    secrets: inherit
