name: Build and Push Server Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "server-spring/**"
      - ".github/workflows/build-server.yml"
  workflow_dispatch:

concurrency:
  group: build-server-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-server:
    permissions:
      contents: read
      packages: write
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ls1intum/learn-hub/spring-server
      docker-file: server-spring/Dockerfile
      docker-context: ./server-spring
      tags: |
        type=sha,format=short,prefix=main-
        latest
    secrets: inherit
